In [6]:
# https://numpy.org/doc/stable/user/index.html
import numpy as np

In [ ]:
wektor = np.array([1, 2, 3])
wektor

array([1, 2, 3])

In [ ]:
lista1 = [4, 5, 6]
wektor = np.array([lista1])

In [ ]:
wektor

array([[4, 5, 6]])

In [ ]:
wektor_kolumnowy = np.array([[1], [2], [3]])
wektor_kolumnowy

array([[1],
       [2],
       [3]])

In [ ]:
macierz = np.array([[1, 2, 3], [4, 5, 6]])
macierz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

In [ ]:
np.linspace(1, 10, 3)

array([ 1. ,  5.5, 10. ])

In [ ]:
# podsumowanie 
# w jaki sposób tworzymy wektory:
# np.array()      # wiemy jaki chcemy wektor dokładnie
# np.arange()     # wiemy jakie chcemy wartości wektora (ale niekoniecznie ile ma ich być)
# np.linspace()  # wiemy ile chcemy elementów, niekoniecznie jakie mają mieć wartości

In [ ]:
macierz = np.array([
    np.linspace(100, 333, 5),
    np.linspace(467, 874, 5),
    np.linspace(250, 550, 5)
])
macierz

array([[100.  , 158.25, 216.5 , 274.75, 333.  ],
       [467.  , 568.75, 670.5 , 772.25, 874.  ],
       [250.  , 325.  , 400.  , 475.  , 550.  ]])

In [ ]:
macierz.shape

(3, 5)

In [ ]:
macierz.size    # rozmiar, czyli iloczyn wymiarów

15

In [ ]:
macierz.ndim    # liczba wymiarów

2

In [ ]:
macierz

array([[100.  , 158.25, 216.5 , 274.75, 333.  ],
       [467.  , 568.75, 670.5 , 772.25, 874.  ],
       [250.  , 325.  , 400.  , 475.  , 550.  ]])

In [ ]:
wektor

array([[4, 5, 6]])

In [ ]:
# Tensor 0D
skalar = [1]
skalar

[1]

In [ ]:
# Tensor 1D
wektor = [1, 2, 3]
wektor

[1, 2, 3]

In [ ]:
# Tensor 2D, pojawiają się i kolumny i wiersze
macierz = np.array([[1, 2, 3], [4, 5, 6]])
macierz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
macierz = np.array([
    np.linspace(100, 333, 5),
    np.linspace(467, 874, 5),
    np.linspace(250, 550, 5)
])
macierz

array([[100.  , 158.25, 216.5 , 274.75, 333.  ],
       [467.  , 568.75, 670.5 , 772.25, 874.  ],
       [250.  , 325.  , 400.  , 475.  , 550.  ]])

In [ ]:
macierz.shape

(3, 5)

In [ ]:
macierz[1][1]   # numeracja od 0

568.75

In [ ]:
macierz[1, 1]   # numeracja od 0

568.75

In [ ]:
macierz.shape   # najpierw wiersze potem kolumny

(3, 5)

In [ ]:
macierz[0]

array([100.  , 158.25, 216.5 , 274.75, 333.  ])

In [ ]:
macierz[0, :]

array([100.  , 158.25, 216.5 , 274.75, 333.  ])

In [ ]:
macierz[:, 0]

array([100., 467., 250.])

In [ ]:
macierz[:, 2:]

array([[216.5 , 274.75, 333.  ],
       [670.5 , 772.25, 874.  ],
       [400.  , 475.  , 550.  ]])

In [ ]:
# dostajemy elementy oznaczone przez "x"
# [o o x x x]
# [o o x x x]
# [o o x x x]

In [ ]:
np.random.random()  # losowa liczba zmiennoprzecinkowa z zakresu [0.0, 1.0]

0.8259730530960576

In [ ]:
np.random.random(10)

array([0.81010985, 0.11150683, 0.50129917, 0.49132033, 0.5216464 ,
       0.54515905, 0.19749483, 0.52739133, 0.7658521 , 0.2472205 ])

In [ ]:
np.random.random(10).ndim

1

In [ ]:
np.random.normal()  # losowa liczba z rozkładu normalnego https://pl.wikipedia.org/wiki/Rozkład_normlany
np.random.uniform() # losowa liczba z roskładu jednostajnego https://pl.wikipedia.org/wiki/Roskład_jednostajny_ciągły

In [ ]:
# opcja dla liczb całkowitych, z powtórzeniami 
np.random.randint(0, 100, size=10)

array([ 8, 51, 34,  2, 36, 38, 33, 18, 18,  4])

In [ ]:
wektor = np.array([20, 17, 67, 456, 100, 6, 12.5])
wektor

array([ 20. ,  17. ,  67. , 456. , 100. ,   6. ,  12.5])

In [ ]:
wektor_wieksze_od_99 = np.where(wektor > 99)
wektor_wieksze_od_99

(array([3, 4]),)

In [ ]:
wektor[wektor_wieksze_od_99]

array([456., 100.])

In [ ]:
# Zadanie 1.
# Stwórz numpy array z wartościami od 1 do 9, wyświetl, a następnie odwróć tę
# tablicę (pierwszy element zostaje ostatnim, itd.)

zadanie = np.arange(1, 10)
print(zadanie)
zadanie = np.flip(zadanie)
print(zadanie)

[1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1]


In [ ]:
zadanie[:-1]

array([9, 8, 7, 6, 5, 4, 3, 2])

In [ ]:
zadanie[::-1] # https://stackoverflow.com/questions/6771428/most-efficient-way-to-reverse-a-numpy-array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# np.fliplr(zadanie)  # dla wymiarów >= 2
# np.flipud(zadanie)  # dla wymiarów >= 2

In [7]:
# Zadanie 2.
# Stwórz następujący numpy array: [1, 23, 4, 31, 1, 1, 4, 23, 4, 1];
# a następnie wypisz wszystkie unikalne (nie powtarzające się) elementy

vector_1 = [1, 23, 4, 31, 1, 1, 4, 23, 4, 1]
np_array = np.array(vector_1)
np.unique(vector_1)

# lub 

# np_array = np.array(vector_1)
# np.unique(np_array)

array([ 1,  4, 23, 31])

In [ ]:
vector_1

[1, 23, 4, 31, 1, 1, 4, 23, 4, 1]

In [8]:
matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix2 = np.array([
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30]
])

In [9]:
print(matrix1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(matrix2)

[[10 10 10]
 [20 20 20]
 [30 30 30]]


In [11]:
np.add(matrix1, matrix2)

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39]])

In [12]:
np.subtract(matrix1, matrix2)

array([[ -9,  -8,  -7],
       [-16, -15, -14],
       [-23, -22, -21]])

In [14]:
matrix1 + matrix2

array([[11, 12, 13],
       [24, 25, 26],
       [37, 38, 39]])

In [15]:
matrix1 - matrix2

array([[ -9,  -8,  -7],
       [-16, -15, -14],
       [-23, -22, -21]])

In [16]:
matrix1 * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [17]:
matrix1 * np.array([10, 20, 30])

array([[ 10,  40,  90],
       [ 40, 100, 180],
       [ 70, 160, 270]])

In [18]:
matrix1.T # Jeśli w macierzt "i" to wiersze a "j" to kolumny, to element ma index x_(i,j),
          # odwrócenie macierzy polega na zamianie "i" oraz "j" miejscami

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [20]:
# Zadanie 3.
# Stwórz macierz 3x3 (używając reshape) z wartościami od 2 do 10

my_matrix = np.arange(2, 11, 1)
my_matrix = my_matrix.reshape(3, 3)
my_matrix
# my_matrix.reshape(3,3)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [21]:
# Zadanie 4. 
# Stwórz tablicę z sześcioma losowymi wartościami z przedziału od 10 do 30

my_matrix = np.random.randint(10, 30, size=6)
my_matrix = my_matrix.reshape(2, 3)
my_matrix
# my_matrix.reshape(2, 3)

array([[11, 19, 23],
       [24, 10, 13]])

In [ ]:
# Zadanie 5.
# Spośród tablicy wartości: [23, 45, 112, 150, 43, 254, 95, 8] wyfiltruj te, 
# które są większe od 100

arr5 = np.array([23, 45, 112, 150, 43, 254, 95, 8])
arr5
# arr5[np.where(arr5 > 100)]

array([ 23,  45, 112, 150,  43, 254,  95,   8])

In [ ]:
# Zadanie 6. 
# Stwórz poniższą macierz 4x4, a następnie:
# wyświetl element z drugiego wiersza i trzeciej kolumny, 
# oblicz jej wyznacznik,
# oblicz jej ślad (sumę elementów na głównej przekątnej),
# znajdź element największy i najmniejszy.

matrix = np.array([
    [1, 15, 4, 13],
    [8, 21, 3, 12],
    [11, 13, 11, 5],
    [32, 13, 0, 2]
])

# (a)
print(matrix[2][3])

print(matrix[1][2]) # cofamy się o 1, bo zaczynamy liczyć od 0
print(matrix[1, 2])

# (b)
print(matrix.diagonal().sum())

# (c)
print(np.max(matrix), np.min(matrix))

5
3
3
35
32 0


In [22]:
# Zadanie 7.
# Stwórz dowolną tablicę wartości, a następnie oblicz średnią i medianę

matrix = np.array([
    [1, 15, 4, 13],
    [8, 21, 3, 12],
    [11, 13, 11, 5],
    [32, 13, 0, 2],
])

print(matrix.mean())
print(np.median(matrix))

10.25
11.0


In [23]:
# Zadanie 8.
# Stwórz dowolną tablicę wartości, a następnie je znormalizuj - tj. od każdego
# elementu tablicy odejmij średnią i podziel przez odchylenie standardowe

arr = np.random.randint(1, 100, 30).reshape(6, 5)
print(arr)
arr = (arr - arr.mean()) / np.std(arr)
print(arr)


[[34 60 45 49 76]
 [78 54 58 52 29]
 [43  9 91 60  4]
 [33 34 12 68 22]
 [79 11 50 31 81]
 [94 89 35 93 54]]
[[-0.65102743  0.34858161 -0.22811591 -0.0743299   0.96372564]
 [ 1.04061864  0.1179026   0.27168861  0.0410096  -0.84325993]
 [-0.30500891 -1.61218996  1.54042316  0.34858161 -1.80442247]
 [-0.68947393 -0.65102743 -1.49685046  0.65615363 -1.11238544]
 [ 1.07906514 -1.53529696 -0.0358834  -0.76636693  1.15595815]
 [ 1.65576267  1.46353016 -0.61258092  1.61731616  0.1179026 ]]


In [24]:
# Zadanie 9.
# Stwórz funkcję, która przyjmuje dwa wektory (oba o tym samym wymiarze) w
# postaci numpy tablicy, a zwróci odległość euklidesową między nimi

u_1 = np.array([1, 3, 5, 2, 0])
u_2 = np.array([6, 3, 1, -1, 2])

print(u_1)
print(u_2)

result = (u_1 - u_2)

print(result)

result = result**2

print(result)

result = sum(result)

print(result)

result = result**1/2

print(result)

[1 3 5 2 0]
[ 6  3  1 -1  2]
[-5  0  4  3 -2]
[25  0 16  9  4]
54
27.0


In [25]:
def euclidian_distance(v1: np.ndarray, v2: np.ndarray) -> float:
  return np.sqrt(((v1 - v2) ** 2).sum())

In [26]:
import numpy as np
import scipy.stats as stats

In [27]:
data1 = [5.01, 5.02, 5.00, 4.99, 4.97]
data2 = [1.01, 1.02, 8.00, 2.99, 0.97]

data1 = np.array(data1)
data2 = np.array(data2)

print(data1.mean(), data2.mean())

4.997999999999999 2.7980000000000005


In [31]:
stats.ttest_1samp(data1, popmean=5)

TtestResult(statistic=-0.23249527748771723, pvalue=0.8275647196019748, df=4)

In [29]:
stats.ttest_1samp(data2, popmean=5)

TtestResult(statistic=-1.6233915217310744, pvalue=0.1798277548227995, df=4)

In [30]:
stats.ttest_ind(data1, data2)

Ttest_indResult(statistic=1.6218844357980349, pvalue=0.143485567629534)

In [ ]:
# popmean=5.0
# stats.ttest_1samp()

In [32]:
data3 = np.arange(1, 100, 1)
data3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [33]:
stats.normaltest(data3)

NormaltestResult(statistic=34.173457336415495, pvalue=3.79601592424177e-08)

In [ ]:
# jeśli p-value < 0.05 to odrzucamy H0 (hipotezę zerową), która mówi, że to jest rozkład normalny
# więc nasze dane nie są z rozkładu normalnego

In [34]:
data4 = np.random.normal(size=10000)
data4[:10,]

array([ 0.19055467, -0.16602419,  0.63907073, -0.32776958, -0.05542919,
        0.80077077,  0.02842018,  1.01653873, -0.80114596, -1.40278415])

In [35]:
stats.normaltest(data4)

NormaltestResult(statistic=0.9800316578799421, pvalue=0.612616697034746)

In [36]:
normal_data = stats.norm.rvs(size=1000)
ks_results = stats.kstest(normal_data, 'norm')
print(ks_results)

KstestResult(statistic=0.03911415474806246, pvalue=0.09133443772672034, statistic_location=0.5075461117630584, statistic_sign=-1)


In [37]:
normal_data = stats.norm.rvs(size=1000) 
shapiro_test_results = stats.shapiro(normal_data)
print(shapiro_test_results) 

ShapiroResult(statistic=0.9985937476158142, pvalue=0.6168428659439087)


In [38]:
stats.levene(data1, data2)

LeveneResult(statistic=1.7580888903553638, pvalue=0.2214699897325906)